---
- name: Recopilar facts básicos con módulo setup
  hosts: all
  gather_facts: no
  vars:
    awx_url: "{{ lookup('env', 'AWX_API_URL') }}"
    awx_token: "{{ lookup('env', 'AWX_OAUTH_TOKEN') }}"
      
  tasks:

    - name: Comprobar conexión con los hosts
      ansible.windows.win_ping:
      register: ping_result
      ignore_unreachable: true

    - name: Mostrar resultado de ping
      debug:
        msg: "{{ inventory_hostname }}: {{ 'CONECTADO' if ping_result is succeeded else 'NO CONECTADO' }}"

    - name: Verificar si existe krb5.log
      stat:
        path: /tmp/krb5.log
      register: krb5_log_exists
      delegate_to: localhost
      run_once: true

    - name: Mostrar krb5.log si existe
      debug:
        msg: "{{ lookup('file', '/tmp/krb5.log') }}"
      when: krb5_log_exists.stat.exists
      delegate_to: localhost
      run_once: true
