
- name: Recopilar facts con módulo raw
  hosts: all
  gather_facts: no
  vars:
    awx_url: "{{ lookup('env', 'AWX_API_URL') }}"
    awx_token: "{{ lookup('env', 'AWX_OAUTH_TOKEN') }}"
    inventario_destino: 3
  
  tasks:
    - name: Obtener información del kernel y sistema operativo
      raw: uname -a
      register: kernel_info

    - name: Obtener información de la distribución Linux
      raw: cat /etc/*release* 2>/dev/null | head -10
      register: os_info
      ignore_errors: yes

    - name: Recopilar información de red (sin ifconfig)
      raw: |
        echo "Interfaces de red:"
        cat /proc/net/dev 2>/dev/null || echo "No network dev info"
        echo "Direcciones IP:"
        hostname -I 2>/dev/null || hostname -i 2>/dev/null || echo "No IP available"
        echo "Interfaces disponibles:"
        ls /sys/class/net/ 2>/dev/null || echo "No network interfaces info"
        echo "Tabla de rutas:"
        cat /proc/net/route 2>/dev/null || echo "No route info"
      register: network_info
      ignore_errors: yes

    - name: Obtener información del procesador
      raw: cat /proc/cpuinfo | grep -E "processor|model name|cpu cores" | head -10
      register: cpu_info
      ignore_errors: yes

    - name: Obtener información de la memoria
      raw: cat /proc/meminfo | grep -E "MemTotal|MemFree"
      register: memory_info
      ignore_errors: yes
      
    - name: Obtener versión de Python
      raw: python --version 2>&1 || python2 --version 2>&1 || python3 --version 2>&1 || echo "Python not found"
      register: python_version
      ignore_errors: yes
      
    - name: Obtener versión de Java
      raw: |
        if command -v java >/dev/null 2>&1; then
          echo "Java Runtime: $(java -version 2>&1 | head -1)"
        else
          echo "Java command not found in PATH"
        fi
        if command -v javac >/dev/null 2>&1; then
          echo "Java Compiler: $(javac -version 2>&1)"
        fi
        echo "JAVA_HOME: ${JAVA_HOME:-Not set}"
      register: java_version
      ignore_errors: yes
    
    - name: Obtener versión de Tomcat
      raw: |
        ps aux | grep -i tomcat | grep -v grep | hea d -3 || echo "No Tomcat processes"
        echo "--- Tomcat Directories ---"
        find /opt /usr/local /home -maxdepth 3 -name "*tomcat*" -type d 2>/dev/null | head -5 || echo "No Tomcat dirs found"
        echo "CATALINA_HOME: ${CATALINA_HOME:-Not set}"
      register: tomcat_version
      ignore_errors: yes
      
    - name: Construir diccionario con los facts
      set_fact:
        filtered_system_facts:
          network_info: "{{ network_info.stdout }}"
          os_version: "{{ os_info.stdout }}"
          kernel_version: "{{ kernel_info.stdout }}"
          memory_details: "{{ memory_info.stdout }}"
          cpu_details: "{{ cpu_info.stdout }}"
          python_version: "{{ python_version.stdout }}"
          java_version: "{{ java_version.stderr }}"
          tomcat_version: "{{ tomcat_version.stdout }}"              
          
    - name: Actualizar host en AWX añadiendo los facts
      awx.awx.host:
        controller_host: "{{ awx_url }}"
        controller_oauthtoken: "{{ awx_token }}"
        inventory: "{{ inventario_destino }}"
        name: "{{ inventory_hostname }}"
        new_name: "{{ original_name }}"
        validate_certs: false
        variables:
          original_name: "{{ original_name }}"
          name: "{{ name }}"
          hostname: "{{ hostname }}"
          ansible_host: "{{ ansible_host }}"
          proxmox:
            proxmox_agent: "{{ proxmox_agent | default('') }}"
            proxmox_agent_interfaces: "{{ proxmox_agent_interfaces | default('') }}"
            proxmox_boot: "{{ proxmox_boot | default('') }}"
            proxmox_cores: "{{ proxmox_cores | default('') }}"
            proxmox_cpu: "{{ proxmox_cpu | default('') }}"
            proxmox_digest: "{{ proxmox_digest | default('') }}"
            proxmox_hotplug: "{{ proxmox_hotplug | default('') }}"
            proxmox_ide0: "{{ proxmox_ide0 | default('') }}"
            proxmox_memory: "{{ proxmox_memory | default('') }}"
            proxmox_meta: "{{ proxmox_meta | default('') }}"
            proxmox_net0: "{{ proxmox_net0 | default('') }}"
            proxmox_node: "{{ proxmox_node | default('') }}"
            proxmox_numa: "{{ proxmox_numa | default('') }}"
            proxmox_ostype: "{{ proxmox_ostype | default('') }}"
            proxmox_qmpstatus: "{{ proxmox_qmpstatus | default('')}}"
            proxmox_scsi0: "{{ proxmox_scsi0 | default('') }}"
            proxmox_scsi1: "{{ proxmox_scsi1 | default('') }}"
            proxmox_scsi2: "{{ proxmox_scsi2 | default('') }}"
            proxmox_scsi3: "{{ proxmox_scsi3 | default('') }}"
            proxmox_scsihw: "{{ proxmox_scsihw | default('') }}"
            proxmox_snapshots: "{{ proxmox_snapshots | default('') }}"
            proxmox_sockets: "{{ proxmox_sockets | default('') }}"
            proxmox_status: "{{ proxmox_status | default('') }}"
            proxmox_vmgenid: "{{ proxmox_vmgenid | default('') }}"
            proxmox_vmid: "{{ proxmox_vmid | default('') }}"
            proxmox_vmtype: "{{ proxmox_vmtype | default('') }}"
          ansible_facts: "{{ filtered_system_facts }}"
      delegate_to: localhost
      throttle: 1
    