---
- name: Recopilar facts y actualizarlos en AWX
  hosts: all
  gather_facts: yes
  vars:
    awx_inventory_id: 3
    ansible_ssh_extra_args: "-o KexAlgorithms=+diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1 -o HostKeyAlgorithms=+ssh-rsa -o MACs=hmac-sha1"
  tasks:

    - name: Mostrar variables AWX para depuración
      debug:
        msg:
          url: "{{ api_url | default('NO DEFINIDA') }}"
          token: "{{ oauth_token | default('NO DEFINIDO') }}"
      delegate_to: localhost

    # Tarea que recopila la información de los hosts que aparece en la
    # pestaña Facts del inventario en AWX.
    - name: Recopilar información del sistema
      setup:

    # Esta tarea obtiene una lista de las variables más relevantes del host.
    - name: Obtener las variables relevantes del host
      set_fact:
        filtered_vars:
          "name": "{{ hostvars[inventory_hostname].name | default([]) }}"
          "parent": "{{ hostvars[inventory_hostname].parent | default([]) }}"
          "parentVApp": "{{ hostvars[inventory_hostname].parentVApp | default([]) }}"
          "permission": "{{ hostvars[inventory_hostname].permission | default([]) }}"
          "recentTask": "{{ hostvars[inventory_hostname].recentTask | default([]) }}"
          "resourcePool": "{{ hostvars[inventory_hostname].resourcePool | default([]) }}"
          "rootSnapshot": "{{ hostvars[inventory_hostname].rootSnapshot | default([]) }}"
          "snapshot": "{{ hostvars[inventory_hostname].snapshot | default([]) }}"
          "triggeredAlarmState": "{{ hostvars[inventory_hostname].triggeredAlarmState | default([]) }}"
          "overallStatus": "{{ hostvars[inventory_hostname].overallStatus | default([]) }}"
          "guest": "{{ hostvars[inventory_hostname].guest | default([]) }}"
          "guestHeartbeatStatus": "{{ hostvars[inventory_hostname].guestHeartbeatStatus | default([]) }}"
          "network": "{{ hostvars[inventory_hostname].network | default([]) }}"
          "value": "{{ hostvars[inventory_hostname].value | default([]) }}"
          "capability": "{{ hostvars[inventory_hostname].capability | default([]) }}"
          "runtime": "{{ hostvars[inventory_hostname].runtime | default([]) }}"
          "availableField": "{{ hostvars[inventory_hostname].availableField | default([]) }}"
          "customValue": "{{ hostvars[inventory_hostname].customValue | default([]) }}"
          "datastore": "{{ hostvars[inventory_hostname].datastore | default([]) }}"
          "effectiveRole": "{{ hostvars[inventory_hostname].effectiveRole | default([]) }}"
          "layout": "{{ hostvars[inventory_hostname].layout | default([]) }}"
          "layoutEx": "{{ hostvars[inventory_hostname].layoutEx | default([]) }}"
          "storage": "{{ hostvars[inventory_hostname].storage | default([]) }}"
          "configIssue": "{{ hostvars[inventory_hostname].configIssue | default([]) }}"
          "configStatus": "{{ hostvars[inventory_hostname].configStatus | default([]) }}"
          "config": "{{ hostvars[inventory_hostname].config | default([]) }}"
          "summary": "{{ hostvars[inventory_hostname].summary | default([]) }}"

    # Tarea que concatena las variables del host recuperadas del inventario para
    # añadir las nuevas variables que hemos averiguado.
    - name: Actualizar la variable del host en AWX
      awx.awx.host:
        controller_host: "{{api_url}}"              # Indicamos la dirección de AWX.
        controller_oauthtoken: "{{oauth_token}}"      # Autorización de acceso a AWX mediante token.
        inventory: "{{awx_inventory_id}}"               # Asignanos el inventario que vamos a modificar.
        name: "{{ inventory_hostname }}"                # Seleccionamos el host al que le añadimos la nueva propiedad.
        validate_certs: false                           # Omitimos comprobación de certificados por tenerlo autofirmado.
        variables: "{{ filtered_vars}}"
      delegate_to: localhost                            # Esta tarea se ejecuta en el servidor de ansible, no en los hosts.
