---
- name: Recopilar facts básicos con módulo setup
  hosts: all
  gather_facts: no
  vars:
    awx_url: "{{ lookup('env', 'AWX_API_URL') }}"
    awx_token: "{{ lookup('env', 'AWX_OAUTH_TOKEN') }}"
    inventario_destino: 3
  
  tasks:

    - name: Comprobar conexión con los hosts
      ansible.windows.win_ping:
      ignore_unreachable: true
      
    - name: Mostrar krb5.log
      ansible.builtin.debug:
        msg: "{{ lookup( 'file', '/tmp/krb5.log' ) }}"
    
