---
- name: Recopilar facts y actualizarlos en AWX
  hosts: all
  gather_facts: yes

  vars:
    awx_api_url: "{{ lookup('env', 'TOWER_HOST') | default('https://awx.example.com', true) }}"
    awx_oauth_token: "{{ lookup('env', 'TOWER_OAUTH_TOKEN') }}"

  tasks:
    - name: Mostrar algunos facts para depuración
      debug:
        msg:
          - "Distribución: {{ ansible_distribution }}"
          - "Versión: {{ ansible_distribution_version }}"
          - "Familia de OS: {{ ansible_os_family }}"
          - "RAM Total (MB): {{ ansible_memtotal_mb }}"
          - "Número de CPUs: {{ ansible_processor_vcpus }}"

    - name: Actualizar variables del host en AWX
      uri:
        url: "{{ awx_api_url }}/api/v2/hosts/{{ inventory_hostname }}/"
        method: PATCH
        headers:
          Authorization: "Bearer {{ awx_oauth_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          variables: |
            {
              "ansible_distribution": "{{ ansible_distribution }}",
              "ansible_distribution_version": "{{ ansible_distribution_version }}",
              "ansible_os_family": "{{ ansible_os_family }}",
              "ansible_memtotal_mb": "{{ ansible_memtotal_mb }}",
              "ansible_processor_vcpus": "{{ ansible_processor_vcpus }}"
            }
        status_code: 200
        validate_certs: false
      delegate_to: localhost
