---
- name: Crear inventario inteligente con filtro de exclusión de grupos
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - awx.awx
  
  vars:
    awx_url: "{{ lookup('env', 'AWX_API_URL') }}"
    awx_token: "{{ lookup('env', 'AWX_OAUTH_TOKEN') }}"
  
    # Detalles del inventario a crear
    inventario_linux_nombre: "PROXMOX Linux Hosts"
    inventario_linux_descripcion: "Hosts de Proxmox con Linux no obsoleto"
    organizacion_nombre: "Default"
    
    # Filtro para el inventario inteligente
    grupo_linux: "os_l26"
    grupo_obsoletos: "legacy_hosts"      # Nombre del grupo a excluir
  
  tasks:
    - name: Comprobar si el inventario ya existe
      awx.awx.inventory_info:
        name: "{{ inventario_linux_nombre }}"
        controller_host: "{{ awx_url }}"
        controller_oauthtoken: "{{ awx_token }}"
        validate_certs: false
      register: inventory_check
      
    - name: Crear inventario inteligente
      awx.awx.inventory:
        name: "{{ inventario_linux_nombre }}"
        description: "{{ inventario_linux_descripcion }}"
        organization: "{{ organizacion_nombre }}"
        host_filter: "groups.name=\"{{ grupo_linux }}\" and not groups.name=\"{{ grupo_obsoletos }}\""
        kind: "smart"
        controller_host: "{{ awx_url }}"
        controller_oauthtoken: "{{ awx_token }}"
        validate_certs: false
      register: inventario_resultado
      when: inventory_check.inventories | length == 0
      
    - name: Mostrar resultado
      debug:
        msg: >
          {% if inventory_check.inventories | length > 0 %}
          El inventario "{{ inventario_linux_nombre }}" ya existe con ID: {{ inventory_check.inventories[0].id }}
          {% else %}
          Inventario inteligente creado con ID: {{ inventario_resultado.id }}
          {% endif %}