- name: Mostrar lista limpia de hosts con saltos de línea reales
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostrar nombres como bloque YAML (saltos de línea visibles)
      run_once: true
      debug:
        msg: >
          {% for host in groups['all'] %}
          {{ host }}
          {% endfor %}
