---
- name: Mostrar facts básicos con módulo setup
  hosts: all
  serial: 1
  gather_facts: no
  any_errors_fatal: false
 
  tasks:

    - name: Recopilar facts estándar
      setup:
        gather_subset:
          - hardware
          - network
          - virtual
          - distribution

    - name: Construir diccionario con los facts
      set_fact:
        filtered_system_facts:
          hostname: "{{ ansible_hostname }}"
          fqdn: "{{ ansible_fqdn | default('') }}"
          ip: "{{ ansible_default_ipv4.address | default('') }}"
          os:
            name: "{{ ansible_distribution }}"
            version: "{{ ansible_distribution_version }}"
            release: "{{ ansible_distribution_release | default('') }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          memory_mb: "{{ ansible_memtotal_mb }}"
          cpu_count: "{{ ansible_processor_count }}"
          collected_at: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"
          
    - name: Mostrar facts
      debug:
        var: filtered_system_facts
