---
- name: Mostrar facts b치sicos con m칩dulo setup
  hosts: all
 
  tasks:

    - name: Recopilar facts est치ndar
      setup:
        gather_subset:
          - hardware
          - network
          - virtual
          - distribution

    - name: Recopilar informaci칩n de paquetes instalados
      package_facts:
        manager: auto

    - name: Obtener versiones de Python instaladas
      set_fact:
        python_versions_detected: "{{ python_versions_list | default([]) }}"
      vars:
        python_packages: "{{ ansible_facts.packages | dict2items | selectattr('key', 'match', '^python[0-9.]*$') | list }}"
        python_versions_list: >-
          {% set result = [] %}
          {% for pkg in python_packages %}
            {% for item in pkg.value %}
              {% set _ = result.append({'name': pkg.key, 'version': item.version}) %}
            {% endfor %}
          {% endfor %}
          {{ result }}

    - name: Obtener versiones de Java instaladas
      set_fact:
        java_versions_detected: "{{ java_versions_list | default([]) }}"
      vars:
        java_packages: "{{ ansible_facts.packages | dict2items | selectattr('key', 'search', 'openjdk|java') | list }}"
        java_versions_list: >-
          {% set result = [] %}
          {% for pkg in java_packages %}
            {% for item in pkg.value %}
              {% set _ = result.append({'name': pkg.key, 'version': item.version}) %}
            {% endfor %}
          {% endfor %}
          {{ result }}

    - name: Obtener versiones de Tomcat instaladas
      set_fact:
        tomcat_versions_detected: "{{ tomcat_versions_list | default([]) }}"
      vars:
        tomcat_packages: "{{ ansible_facts.packages | dict2items | selectattr('key', 'search', 'tomcat') | list }}"
        tomcat_versions_list: >-
          {% set result = [] %}
          {% for pkg in tomcat_packages %}
            {% for item in pkg.value %}
              {% set _ = result.append({'name': pkg.key, 'version': item.version}) %}
            {% endfor %}
          {% endfor %}
          {{ result }}

    - name: Construir diccionario con los facts
      set_fact:
        filtered_system_facts:
          hostname: "{{ ansible_hostname }}"
          fqdn: "{{ ansible_fqdn | default('') }}"
          ip: "{{ ansible_default_ipv4.address | default('') }}"
          os:
            name: "{{ ansible_distribution }}"
            version: "{{ ansible_distribution_version }}"
            release: "{{ ansible_distribution_release | default('') }}"
          kernel: "{{ ansible_kernel }}"
          architecture: "{{ ansible_architecture }}"
          memory_mb: "{{ ansible_memtotal_mb }}"
          cpu_count: "{{ ansible_processor_count }}"
          python_versions: "{{ python_versions_detected }}"
          java_versions: "{{ java_versions_detected }}"
          tomcat_versions: "{{ tomcat_versions_detected }}"
          collected_at: "{{ lookup('pipe', 'date +%Y-%m-%dT%H:%M:%S') }}"
          
    - name: Mostrar facts
      debug:
        var: filtered_system_facts
