---
- name: Generar inventario desde Proxmox
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Obtener lista de VMs desde Proxmox
      community.general.proxmox_vm_info:
        api_user: 'root@pam'
        api_password: '{{ proxmox_pass }}'
        api_host: '192.168.1.52'
      register: proxmox_vms

    - name: Crear inventario dinámico en formato JSON
      copy:
        dest: "/tmp/proxmox_inventory.json"
        content: |
          {
            "_meta": {
              "hostvars": {}
            },
            "proxmox_vms": {
              "hosts": [
                {% for vm in proxmox_vms.resources %}
                  "{{ vm.name }}"{% if not loop.last %},{% endif %}
                {% endfor %}
              ]
            }
          }
