---
- name: Playbook que continúa ante cualquier error
  hosts: all
  gather_facts: false

  tasks:
    - name: Ejecutar comando (aunque falle o no haya conexión)
      command: echo "Hola desde {{ inventory_hostname }}"
