---
- name: Prueba de conexión a hosts windows con Kerberos
  hosts: all
  gather_facts: no
  vars:
    kerberos_user: "{{ lookup('env', 'KRB5_PRINCIPAL') }}"
    kerberos_password: "{{ lookup('env', 'KRB5_PASSWORD') }}"
      
  tasks:

    - name: Obtener ticket Kerberos
      expect:
        command: kinit {{ kerberos_user }}
        responses:
          "Password for": "{{ kerberos_password }}"
        timeout: 30
      delegate_to: localhost
      run_once: true
      register: kinit_result
      ignore_errors: true
      
    - name: Verificar ticket obtenido
      shell: klist
      delegate_to: localhost
      run_once: true
      register: klist_result

    - name: Mostrar resultado klist
      debug:
        var: klist_result
      delegate_to: localhost
      run_once: true        
      
    - name: Obtener versiones de Python instaladas
      win_shell: |
        try {
            $version = & python --version 2>&1
            if ($version -match "Python (\d+\.\d+\.\d+)") {
                @{ name = "Python"; version = $matches[1] } | ConvertTo-Json
            } else { "[]" }
        } catch { "[]" }
      register: python_versions
      ignore_errors: yes

    - name: Mostrar versión de Python instalada
      debug:
        var: python_versions
