---
- name: Playbook de prueba de conexión
  hosts: all
  gather_facts: false
  serial: 1  # Procesar un host a la vez
  
  tasks:
    - name: Mostrar mensaje de prueba
      debug:
        msg: "Conexión exitosa con el host {{ inventory_hostname }}"
