---
- name: Playbook de prueba de conexión
  hosts: all
  gather_facts: false
  serial: 1  # Procesar un host a la vez
  
  tasks:
    
    - name: Echo Hola
      ansible.builtin.command:
        cmd: echo "Hola desde {{ inventory_hostname }}"