---
- name: Playbook de prueba de conexión
  hosts: all
  gather_facts: false

  tasks:
    - name: Ejecutar comando
      command: echo "Hola desde {{ inventory_hostname }}"
      register: resultado
      
    - name: Mostrar resultado
      debug:
        var: resultado
        
