---
- name: Verificar plugin de inventario Proxmox
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Listar módulos disponibles
      shell: ansible-doc -t inventory -l | grep proxmox
      register: available_plugins

    - name: Mostrar plugins disponibles
      debug:
        var: available_plugins.stdout_lines

    - name: Verificar colecciones instaladas
      shell: ansible-galaxy collection list
      register: collections

    - name: Mostrar colecciones
      debug:
        var: collections.stdout_lines

    - name: Verificar archivos del plugin
      shell: find /usr -name "proxmox.py" | grep inventory
      register: plugin_path
 
    - name: Mostrar ruta del plugin
      debug:
        var: plugin_path.stdout_lines
